package api

import (
	"encoding/json"
	"fmt"
	"html"
	"strings"

	"roost/internal/billing"
	"roost/internal/store"
)

// renderInvoiceHTML produces a self-contained, print-ready invoice. It carries
// the elements an EU invoice requires: a unique sequential number, issue date,
// seller and buyer identities with VAT ids, per-line net amounts, the VAT rate
// and amount (or a reverse-charge note), and the gross total.
func renderInvoiceHTML(inv *store.Invoice, appName string) string {
	var seller, buyer map[string]any
	json.Unmarshal([]byte(inv.Seller), &seller)
	json.Unmarshal([]byte(inv.Buyer), &buyer)
	var lines []map[string]any
	json.Unmarshal([]byte(inv.Lines), &lines)

	money := func(c int64) string { return billing.FormatMoney(c, inv.Currency) }
	esc := html.EscapeString

	party := func(m map[string]any) string {
		var b strings.Builder
		add := func(key string) {
			if v, ok := m[key].(string); ok && strings.TrimSpace(v) != "" {
				b.WriteString(esc(v) + "<br>")
			}
		}
		add("company")
		add("name")
		add("address")
		// city + postal on one line
		city, _ := m["city"].(string)
		postal, _ := m["postal_code"].(string)
		if strings.TrimSpace(city+postal) != "" {
			b.WriteString(esc(strings.TrimSpace(postal+" "+city)) + "<br>")
		}
		add("country")
		if v, ok := m["vat_id"].(string); ok && strings.TrimSpace(v) != "" {
			b.WriteString("VAT: " + esc(v) + "<br>")
		}
		add("email")
		return b.String()
	}

	var rows strings.Builder
	for _, l := range lines {
		desc, _ := l["description"].(string)
		qty := jsonNum(l["quantity"])
		unit := int64(jsonNum(l["unit_cents"]))
		net := int64(jsonNum(l["net_cents"]))
		rows.WriteString(fmt.Sprintf(
			`<tr><td>%s</td><td class="r">%d</td><td class="r">%s</td><td class="r">%s</td></tr>`,
			esc(desc), int(qty), money(unit), money(net)))
	}

	vatRow := fmt.Sprintf(`<tr><td>VAT (%.2f%%)</td><td class="r">%s</td></tr>`,
		float64(inv.VATRate)/100, money(inv.VATCents))
	if inv.ReverseCharge {
		vatRow = `<tr><td>VAT (reverse charge)</td><td class="r">` + money(0) + `</td></tr>`
	}

	notes := ""
	if inv.Notes != "" {
		notes = `<p class="notes">` + esc(inv.Notes) + `</p>`
	}
	paid := ""
	if inv.PaidAt != nil && *inv.PaidAt != "" {
		paid = `<span class="paid">PAID</span>`
	}

	return `<!doctype html><html><head><meta charset="utf-8">
<title>Invoice ` + esc(inv.Number) + `</title>
<style>
  :root { color-scheme: light; }
  body { font: 14px/1.5 -apple-system, "Segoe UI", Roboto, sans-serif; color: #111; max-width: 800px; margin: 2rem auto; padding: 0 1.5rem; }
  header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #111; padding-bottom: 1rem; }
  h1 { font-size: 1.6rem; margin: 0; }
  .muted { color: #666; }
  .parties { display: flex; justify-content: space-between; gap: 2rem; margin: 2rem 0; }
  .parties h3 { font-size: .8rem; text-transform: uppercase; letter-spacing: .05em; color: #666; margin: 0 0 .4rem; }
  table { width: 100%; border-collapse: collapse; margin-top: 1rem; }
  th, td { text-align: left; padding: .5rem .4rem; border-bottom: 1px solid #ddd; }
  th { font-size: .75rem; text-transform: uppercase; color: #666; }
  .r { text-align: right; }
  .totals { width: 40%; margin-left: auto; margin-top: 1rem; }
  .totals td { border: none; padding: .25rem .4rem; }
  .totals tr:last-child td { border-top: 2px solid #111; font-weight: 700; font-size: 1.1rem; }
  .notes { margin-top: 2rem; padding: .8rem 1rem; background: #f6f6f6; border-radius: 6px; font-size: .85rem; }
  .paid { display: inline-block; margin-top: .3rem; padding: .1rem .5rem; background: #1a7f37; color: #fff; border-radius: 4px; font-size: .8rem; font-weight: 700; }
  footer { margin-top: 3rem; color: #999; font-size: .75rem; text-align: center; }
  @media print { body { margin: 0; } }
</style></head><body>
<header>
  <div><h1>Invoice</h1><div class="muted">` + esc(inv.Number) + `</div>` + paid + `</div>
  <div class="r muted">
    <strong>` + esc(appName) + `</strong><br>
    Issued: ` + esc(dateOnly(inv.IssuedAt)) + `<br>` +
		dueLine(inv) + `
  </div>
</header>
<div class="parties">
  <div><h3>From</h3>` + party(seller) + `</div>
  <div><h3>Bill to</h3>` + party(buyer) + `</div>
</div>
<table>
  <thead><tr><th>Description</th><th class="r">Qty</th><th class="r">Unit</th><th class="r">Net</th></tr></thead>
  <tbody>` + rows.String() + `</tbody>
</table>
<table class="totals">
  <tr><td>Net</td><td class="r">` + money(inv.NetCents) + `</td></tr>
  ` + vatRow + `
  <tr><td>Total</td><td class="r">` + money(inv.GrossCents) + `</td></tr>
</table>
` + notes + `
<footer>Generated by ` + esc(appName) + ` · This invoice was issued electronically and is valid without a signature.</footer>
</body></html>`
}

func dueLine(inv *store.Invoice) string {
	if inv.DueAt == nil || *inv.DueAt == "" {
		return ""
	}
	return "Due: " + html.EscapeString(dateOnly(*inv.DueAt)) + "<br>"
}

func dateOnly(iso string) string {
	if len(iso) >= 10 {
		return iso[:10]
	}
	return iso
}

func jsonNum(v any) float64 {
	switch n := v.(type) {
	case float64:
		return n
	case int64:
		return float64(n)
	case int:
		return float64(n)
	}
	return 0
}
