package store

import (
	"testing"
)

// TestErrorPathsOnClosedDatabase drives every mutating and listing query
// against a closed connection so the "if err != nil { return ... }" branches
// after each Exec/Query are executed. It asserts only that an error surfaces
// (never a panic) — the happy paths are covered by the focused tests.
func TestErrorPathsOnClosedDatabase(t *testing.T) {
	s := newStore(t)
	// Close the underlying pool; every subsequent query must error, not panic.
	if err := s.db.Close(); err != nil {
		t.Fatalf("close: %v", err)
	}

	// A tiny assertion helper: the call must return a non-nil error.
	errs := 0
	must := func(name string, err error) {
		if err == nil {
			t.Errorf("%s: expected an error on a closed database", name)
		} else {
			errs++
		}
	}
	// For funcs returning (T, error) we only care about the error.
	mustList := func(name string, err error) { must(name, err) }

	ptrInt := func(v int64) *int64 { return &v }

	// ---- users ----
	must("CreateUser", s.CreateUser(&User{UUID: "u", Username: "u", Email: "u@e", Password: "p"}))
	must("UpdateUser", s.UpdateUser(&User{ID: 1}))
	must("DeleteUser", s.DeleteUser(1))
	_, err := s.Users("")
	mustList("Users", err)
	_, err = s.SearchUsers("x", 5)
	mustList("SearchUsers", err)
	_, err = s.CountUsers()
	must("CountUsers", err)
	must("CreateSession", s.CreateSession(&Session{TokenHash: "h", UserID: 1, ExpiresAt: "z"}))
	must("PruneSessions", s.PruneSessions())
	must("CreateAPIKey", s.CreateAPIKey(&APIKey{UserID: 1, Identifier: "i", TokenHash: "h", AllowedIPs: "[]"}))
	_, err = s.APIKeysForUser(1, KeyTypeAccount)
	mustList("APIKeysForUser", err)
	must("DeleteAPIKey", s.DeleteAPIKey(1, "i", KeyTypeAccount))
	_, err = s.SSHKeysForUser(1)
	mustList("SSHKeysForUser", err)
	must("CreateSSHKey", s.CreateSSHKey(&SSHKey{UserID: 1, Name: "n", Fingerprint: "f", PublicKey: "k"}))
	must("DeleteSSHKeyByFingerprint", s.DeleteSSHKeyByFingerprint(1, "f"))
	must("ReplaceRecoveryTokens", s.ReplaceRecoveryTokens(1, []string{"a"}))
	_, err = s.ConsumeRecoveryToken(1, "a")
	must("ConsumeRecoveryToken", err)

	// ---- locations & nodes ----
	_, err = s.Locations()
	mustList("Locations", err)
	must("CreateLocation", s.CreateLocation(&Location{Short: "s"}))
	must("UpdateLocation", s.UpdateLocation(&Location{ID: 1}))
	must("DeleteLocation", s.DeleteLocation(1))
	_, err = s.Nodes()
	mustList("Nodes", err)
	must("CreateNode", s.CreateNode(&Node{UUID: "n", Name: "n", LocationID: 1}))
	must("UpdateNode", s.UpdateNode(&Node{ID: 1}))
	must("DeleteNode", s.DeleteNode(1))
	must("ResetNodeToken", s.ResetNodeToken(&Node{ID: 1}))
	_, _, _, err = s.NodeUsage(1)
	must("NodeUsage", err)
	_, err = s.AllocationsForNode(1)
	mustList("AllocationsForNode", err)
	_, err = s.AllocationsForServer(1)
	mustList("AllocationsForServer", err)
	_, err = s.CreateAllocations(1, "127.0.0.1", nil, []int{25565})
	must("CreateAllocations", err)
	must("UpdateAllocation", s.UpdateAllocation(&Allocation{ID: 1}))
	must("DeleteAllocation", s.DeleteAllocation(1))

	// ---- database hosts & mounts ----
	_, err = s.DatabaseHosts()
	mustList("DatabaseHosts", err)
	must("CreateDatabaseHost", s.CreateDatabaseHost(&DatabaseHost{Name: "h", Host: "h", Port: 1, Username: "u", Password: "p"}))
	must("UpdateDatabaseHost", s.UpdateDatabaseHost(&DatabaseHost{ID: 1}))
	must("DeleteDatabaseHost", s.DeleteDatabaseHost(1))
	_, err = s.Mounts()
	mustList("Mounts", err)
	must("CreateMount", s.CreateMount(&Mount{UUID: "m", Name: "m", Source: "/a", Target: "/b"}))
	must("UpdateMount", s.UpdateMount(&Mount{ID: 1}))
	must("DeleteMount", s.DeleteMount(1))
	_, err = s.MountsForServer(1)
	mustList("MountsForServer", err)
	must("SetMountServer", s.SetMountServer(1, 1, true))

	// ---- nests & eggs ----
	_, err = s.Nests()
	mustList("Nests", err)
	must("CreateNest", s.CreateNest(&Nest{UUID: "n", Author: "a", Name: "n"}))
	must("UpdateNest", s.UpdateNest(&Nest{ID: 1}))
	must("DeleteNest", s.DeleteNest(1))
	_, err = s.EggsForNest(1)
	mustList("EggsForNest", err)
	must("CreateEgg", s.CreateEgg(&Egg{UUID: "e", NestID: 1, Name: "e"}))
	must("UpdateEgg", s.UpdateEgg(&Egg{ID: 1}))
	must("DeleteEgg", s.DeleteEgg(1))
	_, err = s.EggVariables(1)
	mustList("EggVariables", err)
	must("CreateEggVariable", s.CreateEggVariable(&EggVariable{EggID: 1, Name: "v", EnvVariable: "V"}))
	must("UpdateEggVariable", s.UpdateEggVariable(&EggVariable{ID: 1}))
	must("DeleteEggVariable", s.DeleteEggVariable(1))

	// ---- servers ----
	_, err = s.Servers()
	mustList("Servers", err)
	_, err = s.ServersForNode(1)
	mustList("ServersForNode", err)
	_, err = s.ServersForUser(1)
	mustList("ServersForUser", err)
	_, err = s.ServersOwnedBy(1)
	mustList("ServersOwnedBy", err)
	must("CreateServer", s.CreateServer(&Server{UUID: "s", UUIDShort: "s", NodeID: 1, Name: "s", OwnerID: 1, NestID: 1, EggID: 1, Startup: "x", Image: "i"}))
	must("UpdateServer", s.UpdateServer(&Server{ID: 1}))
	must("DeleteServer", s.DeleteServer(1))
	_, err = s.CountServers()
	must("CountServers", err)
	_, err = s.ServerVariableValues(1)
	mustList("ServerVariableValues", err)
	must("SetServerVariable", s.SetServerVariable(1, 1, "v"))
	_, err = s.SubusersForServer(1)
	mustList("SubusersForServer", err)
	must("CreateSubuser", s.CreateSubuser(&Subuser{UserID: 1, ServerID: 1, Permissions: "[]"}))
	must("UpdateSubuser", s.UpdateSubuser(&Subuser{ID: 1}))
	must("DeleteSubuser", s.DeleteSubuser(1, 1))
	_, err = s.DatabasesForServer(1)
	mustList("DatabasesForServer", err)
	must("CreateServerDatabase", s.CreateServerDatabase(&ServerDatabase{ServerID: 1, DatabaseHostID: 1, Database: "d", Username: "u", Password: "p"}))
	must("UpdateServerDatabase", s.UpdateServerDatabase(&ServerDatabase{ID: 1}))
	must("DeleteServerDatabase", s.DeleteServerDatabase(1))
	_, err = s.CountDatabasesForServer(1)
	must("CountDatabasesForServer", err)

	// ---- schedules & backups ----
	_, err = s.SchedulesForServer(1)
	mustList("SchedulesForServer", err)
	_, err = s.DueSchedules()
	mustList("DueSchedules", err)
	must("CreateSchedule", s.CreateSchedule(&Schedule{ServerID: 1, Name: "s"}))
	must("UpdateSchedule", s.UpdateSchedule(&Schedule{ID: 1}))
	must("DeleteSchedule", s.DeleteSchedule(1))
	_, err = s.TasksForSchedule(1)
	mustList("TasksForSchedule", err)
	must("CreateTask", s.CreateTask(&ScheduleTask{ScheduleID: 1, Action: "command"}))
	must("UpdateTask", s.UpdateTask(&ScheduleTask{ID: 1}))
	must("DeleteTask", s.DeleteTask(1))
	_, err = s.BackupsForServer(1)
	mustList("BackupsForServer", err)
	_, err = s.CountBackupsForServer(1)
	must("CountBackupsForServer", err)
	must("CreateBackup", s.CreateBackup(&Backup{ServerID: 1, UUID: "b", Name: "b", IgnoredFiles: "[]", Disk: "wings"}))
	must("UpdateBackup", s.UpdateBackup(&Backup{ID: 1}))

	// ---- activity & settings ----
	must("LogActivity", s.LogActivity(&ActivityLog{Event: "e", Properties: "{}", Timestamp: "z"}))
	_, err = s.ActivityForActor(1, 10)
	mustList("ActivityForActor", err)
	_, err = s.ActivityForSubject("server", 1, 10)
	mustList("ActivityForSubject", err)
	must("SetSetting", s.SetSetting("k", "v"))
	_, err = s.Settings()
	mustList("Settings", err)

	// ---- billing ----
	_, err = s.Products(true)
	mustList("Products", err)
	must("CreateProduct", s.CreateProduct(&Product{Name: "p", EggID: 1}))
	must("UpdateProduct", s.UpdateProduct(&Product{ID: 1}))
	must("DeleteProduct", s.DeleteProduct(1))
	_, err = s.BillingProfile(1)
	must("BillingProfile", err)
	must("UpsertBillingProfile", s.UpsertBillingProfile(&BillingProfile{UserID: 1}))
	must("CreateOrder", s.CreateOrder(&Order{UUID: "o", UserID: 1, ProductID: 1, Provider: "stripe", NetCents: 1, GrossCents: 1, Currency: "EUR"}))
	must("UpdateOrder", s.UpdateOrder(&Order{ID: 1, ServerID: ptrInt(1)}))
	_, err = s.OrdersForUser(1)
	mustList("OrdersForUser", err)
	_, err = s.Orders()
	mustList("Orders", err)
	must("CreateSubscription", s.CreateSubscription(&Subscription{UUID: "s", UserID: 1, ProductID: 1, Provider: "stripe"}))
	must("UpdateSubscription", s.UpdateSubscription(&Subscription{ID: 1}))
	_, err = s.SubscriptionsForUser(1)
	mustList("SubscriptionsForUser", err)
	must("CreateInvoice", s.CreateInvoice(&Invoice{UserID: 1, Currency: "EUR", Seller: "{}", Buyer: "{}", Lines: "[]", IssuedAt: "z"}, "INV"))
	must("MarkInvoicePaid", s.MarkInvoicePaid(1, "z"))
	_, err = s.InvoicesForUser(1)
	mustList("InvoicesForUser", err)
	_, err = s.Invoices()
	mustList("Invoices", err)

	// ---- single-row scan error branches (closed db → non-ErrNoRows) ----
	_, err = s.UserByID(1)
	must("UserByID", err)
	_, err = s.UserByEmail("x")
	must("UserByEmail", err)
	_, err = s.UserByUsername("x")
	must("UserByUsername", err)
	_, err = s.UserByExternalID("x")
	must("UserByExternalID", err)
	_, err = s.SessionUser("h")
	must("SessionUser", err)
	_, err = s.APIKeyByIdentifier("i")
	must("APIKeyByIdentifier", err)
	_, err = s.LocationByID(1)
	must("LocationByID", err)
	_, err = s.NodeByID(1)
	must("NodeByID", err)
	_, err = s.NodeByTokenID("t")
	must("NodeByTokenID", err)
	_, err = s.AllocationByID(1)
	must("AllocationByID", err)
	_, err = s.FreeAllocation(1)
	must("FreeAllocation", err)
	_, err = s.DatabaseHostByID(1)
	must("DatabaseHostByID", err)
	_, err = s.MountByID(1)
	must("MountByID", err)
	_, err = s.NestByID(1)
	must("NestByID", err)
	_, err = s.NestByName("n")
	must("NestByName", err)
	_, err = s.EggByID(1)
	must("EggByID", err)
	_, err = s.EggByUUID("u")
	must("EggByUUID", err)
	_, err = s.EggVariableByID(1)
	must("EggVariableByID", err)
	_, err = s.ServerByID(1)
	must("ServerByID", err)
	_, err = s.ServerByUUID("u")
	must("ServerByUUID", err)
	_, err = s.ServerByExternalID("x")
	must("ServerByExternalID", err)
	_, err = s.ServerByIdentifier("x")
	must("ServerByIdentifier", err)
	_, err = s.Subuser(1, 1)
	must("Subuser", err)
	_, err = s.ServerDatabaseByID(1)
	must("ServerDatabaseByID", err)
	_, err = s.ScheduleByID(1)
	must("ScheduleByID", err)
	_, err = s.TaskByID(1)
	must("TaskByID", err)
	_, err = s.BackupByUUID("b")
	must("BackupByUUID", err)
	_, err = s.ProductByID(1)
	must("ProductByID", err)
	_, err = s.OrderByID(1)
	must("OrderByID", err)
	_, err = s.OrderByUUID("o")
	must("OrderByUUID", err)
	_, err = s.OrderByProviderRef("stripe", "r")
	must("OrderByProviderRef", err)
	_, err = s.SubscriptionByID(1)
	must("SubscriptionByID", err)
	_, err = s.SubscriptionByProviderRef("stripe", "r")
	must("SubscriptionByProviderRef", err)
	_, err = s.InvoiceByID(1)
	must("InvoiceByID", err)
	_, err = s.InvoiceByNumber("n")
	must("InvoiceByNumber", err)
	_, err = s.InvoiceByOrder(1)
	must("InvoiceByOrder", err)

	if errs < 60 {
		t.Errorf("only %d error branches exercised; expected the full set", errs)
	}
}
